"""empty message

Revision ID: 22afef21c671
Revises: 704de597288c
Create Date: 2022-05-09 17:10:22.872909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22afef21c671'
down_revision = '704de597288c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'code', type_='foreignkey')
    op.create_foreign_key(None, 'code', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.drop_column('code', 'source')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.add_column('log', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_log_timestamp'), 'log', ['timestamp'], unique=False)
    op.drop_column('log', 'log')
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.add_column('log', sa.Column('log', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_log_timestamp'), table_name='log')
    op.drop_column('log', 'timestamp')
    op.create_foreign_key(None, 'comment', 'user', ['username'], ['username'])
    op.add_column('code', sa.Column('source', sa.VARCHAR(length=10000), nullable=True))
    op.drop_constraint(None, 'code', type_='foreignkey')
    op.create_foreign_key(None, 'code', 'problem', ['problem_id'], ['id'])
    # ### end Alembic commands ###
