"""empty message

Revision ID: 3a558159ef7d
Revises: f75fa96fb32f
Create Date: 2022-05-12 14:31:55.071118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a558159ef7d'
down_revision = 'f75fa96fb32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'c_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('c_name', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
