"""empty message

Revision ID: 657cc111aa61
Revises: d49d9cff02d6
Create Date: 2022-05-10 20:19:39.033436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657cc111aa61'
down_revision = 'd49d9cff02d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('total_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'total_length')
    # ### end Alembic commands ###
