"""empty message

Revision ID: 8d7728b14660
Revises: ac62b61dc9fe
Create Date: 2022-05-14 19:37:40.654853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7728b14660'
down_revision = 'ac62b61dc9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta', sa.Column('room_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'ta', type_='foreignkey')
    op.create_foreign_key(None, 'ta', 'room', ['room_id'], ['id'])
    op.drop_column('ta', 'pf')
    op.drop_column('ta', 'problem_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta', sa.Column('problem_id', sa.INTEGER(), nullable=True))
    op.add_column('ta', sa.Column('pf', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'ta', type_='foreignkey')
    op.create_foreign_key(None, 'ta', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ta', 'room_id')
    # ### end Alembic commands ###
