"""empty message

Revision ID: 9534b4503f68
Revises: ffe9cefe455c
Create Date: 2022-05-12 14:30:42.393630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9534b4503f68'
down_revision = 'ffe9cefe455c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'room_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_name', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
