"""empty message

Revision ID: ac62b61dc9fe
Revises: 3a558159ef7d
Create Date: 2022-05-12 14:34:11.818725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac62b61dc9fe'
down_revision = '3a558159ef7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'c_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('c_name', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
