"""empty message

Revision ID: d49d9cff02d6
Revises: 22afef21c671
Create Date: 2022-05-10 13:57:34.133240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49d9cff02d6'
down_revision = '22afef21c671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_log_username'), 'log', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_username'), table_name='log')
    op.drop_column('log', 'username')
    # ### end Alembic commands ###
