"""empty message

Revision ID: f75fa96fb32f
Revises: 9534b4503f68
Create Date: 2022-05-12 14:31:32.085940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75fa96fb32f'
down_revision = '9534b4503f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'c_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('c_name', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
