"""empty message

Revision ID: ffe9cefe455c
Revises: 657cc111aa61
Create Date: 2022-05-12 14:29:37.994801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe9cefe455c'
down_revision = '657cc111aa61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('c_name', sa.String(length=128), nullable=True))
    op.drop_column('room', 'room_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_name', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('room', 'c_name')
    # ### end Alembic commands ###
